profile: "prod"
appId: ""
appSlug: "" 
promoteToChannelIds: []
promoteToChannelNames: []
charts: [
  {
    path: "./chart/something",
    chartVersion: "",
    appVersion: "",
  },
  {
      path: "./chart/new-chart/*",
      chartVersion: "",
      appVersion: "",
  }
]
preflights: [
  {
      path: "./preflights/stuff",
      valuesPath: "./chart/something", # directory to corresponding helm chart
  }
]
releaseLabel: ""  ## some sort of semver pattern?
manifests: ["replicated/**/*.yaml"]
repl-lint:
  version: 1
  linters:
    helm:
      disabled: false
      strict: false
    preflight:
      disabled: false
      strict: true
    support-bundle:
      disabled: false
      strict: false
    embedded-cluster:
      disabled: true
      strict: false
    kots:
      disabled: true
      strict: false
  tools:
    helm: "3.19.0"
    preflight: "0.123.9"
    support-bundle: "0.123.9"