on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, ready_for_review]

name: "depot: PR"

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Depot PR workflow registered"
