appId: ""
appSlug: "" 
promoteToChannelIds: []
promoteToChannelNames: []
charts: [
  {
    path: "../pkg/imageextract/testdata/helm-chart",
    chartVersion: "",
    appVersion: "",
  },
]
preflights: [
  {
      path: "./preflights/stuff",
      valuesPath: "./chart/something", # directory to corresponding helm chart
  }
]
releaseLabel: ""  ## some sort of semver pattern?
manifests: ["replicated/**/*.yaml"]
repl-lint:
  version: 1
  linters:
    helm:
      disabled: false
    preflight:
      disabled: false
    support-bundle:
      disabled: false
    embedded-cluster:
      disabled: true
    kots:
      disabled: true
  tools:
    helm: "3.19.0"
    preflight: "0.123.9"
    support-bundle: "0.123.9"