appId: ""
appSlug: "" 
promoteToChannelIds: []
promoteToChannelNames: []
charts: [
  {
    path: "./helm-chart",
    chartVersion: "",
    appVersion: "",
  },
]
preflights: [
  {
      path: "./preflights/**",
  }
]
releaseLabel: ""  ## some sort of semver pattern?
manifests: ["./support-bundles/**", "./embedded-cluster/**", "./kots/**"]
repl-lint:
  version: 1
  linters:
    helm:
      disabled: false
    preflight:
      disabled: false
    support-bundle:
      disabled: false
    embedded-cluster:
      disabled: false
    kots:
      disabled: false
  tools:
    helm: "latest"
    preflight: "latest"
    support-bundle: "latest"
    kots: "latest"
