appId: ""
appSlug: "" 
promoteToChannelIds: []
promoteToChannelNames: []
charts: [
  {
    path: "./helm-chart",
    chartVersion: "",
    appVersion: "",
  },
]
preflights: [
  {
      path: "./preflights/**",
      valuesPath: "./chart/something", # directory to corresponding helm chart
  }
]
releaseLabel: ""  ## some sort of semver pattern?
manifests: ["./support-bundles/**"]
repl-lint:
  version: 1
  linters:
    helm:
      disabled: false
    preflight:
      disabled: false
    support-bundle:
      disabled: false
  tools:
    helm: "3.19.0"
    preflight: "0.123.9"
    support-bundle: "0.123.9"