apiVersion: kots.io/v1beta2
kind: HelmChart
metadata:
  name: sample-app
spec:
  chart:
    name: sample-app
    chartVersion: 1.0.0
  # Builder values override chart values for v1beta3 preflights
  builder:
    testMode: true
    environment: production
    replicas: 3
    database:
      enabled: true
      host: db.example.com
      port: 5432
