package cmd

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"syscall"
	"text/template"
	"time"

	"github.com/pkg/errors"
	"github.com/replicatedhq/replicated/pkg/credentials"
	"github.com/replicatedhq/replicated/pkg/kotsclient"
	"github.com/replicatedhq/replicated/pkg/platformclient"
	"github.com/replicatedhq/replicated/pkg/types"
	"github.com/spf13/cobra"
)

const defaultPreviewImage = "registry.replicated.com/library/ep-preview:latest"

// Bind the host port to 127.0.0.1 so the preview (including the customer
// dropdown) isn't reachable from the local network — otherwise anyone on the
// vendor's wifi could enumerate customers and view licenses.
// Mount the content dir read-only: the server only reads, and :ro hardens
// against a future feature or compromised image accidentally mutating the
// vendor's content repo.
// The internal Next.js PORT is set to match the host port so Next.js's own
// startup banner ("Local: http://localhost:<port>") reports the right URL —
// otherwise vendors see conflicting ports in the CLI output vs the container
// log when we auto-pick a non-default port.
const composeTemplate = `# Auto-generated by replicated CLI — do not edit manually
services:
  ep-preview:
    image: {{.Image}}
    ports:
      - "127.0.0.1:{{.Port}}:{{.Port}}"
    volumes:
      - '{{.AbsPath}}:/repo:ro'
    environment:
      - PORT={{.Port}}
      - REPLICATED_APP={{.AppSlug}}
      - REPLICATED_API_TOKEN=${REPLICATED_API_TOKEN}
      - EP_PREVIEW_CUSTOMERS_JSON=${EP_PREVIEW_CUSTOMERS_JSON}
`

type composeTemplateData struct {
	AppSlug string
	Port    int
	AbsPath string
	Image   string
}

func (r *runners) InitEnterprisePortalPreviewCmd(parent *cobra.Command) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "preview <path>",
		Short: "Preview Enterprise Portal v2 content locally",
		Long: `Start a local preview of your Enterprise Portal v2 content.

Mounts the specified content repository into a Docker container running the
real EP v2 app. Content is read directly from disk — no commit or push needed.

If REPLICATED_API_TOKEN is set, the preview toolbar will show a customer
switcher so you can preview as any of your real customers.`,
		Example: `  # Preview local content on port 3000
  replicated enterprise-portal preview ./enterprise-portal-myapp

  # Preview on a custom port
  replicated enterprise-portal preview ./enterprise-portal-myapp --port 8080`,
		RunE: r.enterprisePortalPreview,
		Args: cobra.ExactArgs(1),
		// Override parent's pre-run. The preview command runs entirely locally
		// and doesn't need API access or app resolution from the CLI side.
		PersistentPreRunE: func(cmd *cobra.Command, args []string) error { return nil },
		SilenceUsage:      true,
	}
	parent.AddCommand(cmd)

	cmd.Flags().IntVar(&r.args.enterprisePortalPreviewPort, "port", 3000, "Local port to expose the preview on")
	cmd.Flags().StringVar(&r.args.enterprisePortalPreviewImage, "image", defaultPreviewImage, "Docker image to use for the preview")
	cmd.Flags().MarkHidden("image")

	return cmd
}

func (r *runners) enterprisePortalPreview(cmd *cobra.Command, args []string) error {
	contentPath := args[0]
	port := r.args.enterprisePortalPreviewPort

	absPath, err := filepath.Abs(contentPath)
	if err != nil {
		return errors.Wrap(err, "resolve content path")
	}

	if _, err := os.Stat(absPath); err != nil {
		return errors.Errorf("content path does not exist: %s", contentPath)
	}

	// Resolve the app slug using the same order as the rest of the CLI:
	//   1. --app flag (stored in the package-level appSlugOrID)
	//   2. default app set via `replicated default app <slug>` (cache.DefaultApp)
	//   3. REPLICATED_APP env var
	appSlug := appSlugOrID
	if appSlug == "" && cache != nil {
		appSlug = cache.DefaultApp
	}
	if appSlug == "" {
		appSlug = os.Getenv("REPLICATED_APP")
	}
	if appSlug == "" {
		return errors.New("app required: pass --app, set REPLICATED_APP, or set a default with `replicated default app <slug>`")
	}

	// Resolve the API token using the same sources the rest of the CLI uses:
	//   1. --token flag (stored in the package-level apiToken)
	//   2. REPLICATED_API_TOKEN env var
	//   3. stored profile credentials (from `replicated login` / `replicated profile`)
	token := apiToken
	if token == "" {
		token = os.Getenv("REPLICATED_API_TOKEN")
	}
	if token == "" {
		var profileName string
		if profileNameFlag != "" {
			profileName = profileNameFlag
		} else if defaultProfileName, err := credentials.GetDefaultProfile(); err == nil {
			profileName = defaultProfileName
		}
		if creds, err := credentials.GetCredentialsWithProfile(profileName); err == nil {
			token = creds.APIToken
			// If the token came from a profile, the profile may also point at a
			// non-default vendor API (staging, a namespace, etc). Resolve it so
			// buildPreviewCustomersEnv hits the same environment the token is for.
			if creds.IsProfile && profileName != "" {
				if origins, err := credentials.ResolveOriginsFromProfileName(profileName); err == nil && origins.VendorAPI != "" {
					platformOrigin = strings.TrimRight(origins.VendorAPI, "/")
				}
			}
		}
	}
	// Token is optional: without it the customer switcher in the preview UI
	// is hidden, but the rest of the preview still works with mock data.

	// Probe for a free port starting from the requested one. Without this, a
	// busy default port makes `docker compose up` fail with a cryptic
	// "bind: address already in use" after we've already told the user the
	// preview is on that port. Keep it short — ~20 attempts covers the common
	// case; beyond that assume something else is going on and let docker error.
	if free, err := findFreePort(port, 20); err == nil {
		if free != port {
			fmt.Fprintf(os.Stderr, "Port %d is in use; using %d instead\n", port, free)
			port = free
		}
	}

	// Write docker-compose.preview.yml into the content directory
	composePath := filepath.Join(absPath, "docker-compose.preview.yml")
	f, err := os.Create(composePath)
	if err != nil {
		return errors.Wrap(err, "create docker-compose.preview.yml")
	}
	defer f.Close()

	tmpl, err := template.New("compose").Parse(composeTemplate)
	if err != nil {
		return errors.Wrap(err, "parse compose template")
	}
	image := r.args.enterprisePortalPreviewImage

	if err := tmpl.Execute(f, composeTemplateData{
		AppSlug: appSlug,
		Port:    port,
		AbsPath: escapeComposeScalar(absPath),
		Image:   image,
	}); err != nil {
		return errors.Wrap(err, "write docker-compose.preview.yml")
	}
	f.Close()

	fmt.Fprintf(os.Stderr, "Starting EP v2 preview for app %q on http://localhost:%d\n", appSlug, port)

	// Pre-fetch the real customer list + licenses so the preview toolbar can
	// offer a switcher. Without a token we skip this and the switcher is hidden.
	customersB64 := ""
	if token != "" {
		b64, err := buildPreviewCustomersEnv(appSlug, token)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Warning: could not fetch customers (%v) — switcher will be hidden\n", err)
		} else {
			customersB64 = b64
			fmt.Fprintf(os.Stderr, "Loaded customers — switcher available in preview UI\n")
		}
	} else {
		fmt.Fprintf(os.Stderr, "No API token found — preview will use mock customer data\n")
	}
	fmt.Fprintf(os.Stderr, "Press Ctrl+C to stop.\n\n")

	// Only auto-pull when using the default (registry) image. A custom --image
	// is likely a locally-built tag that won't exist in any registry.
	dockerArgs := []string{"compose", "-f", composePath, "up"}
	if image == defaultPreviewImage {
		dockerArgs = append(dockerArgs, "--pull", "always")
	}
	dockerCmd := exec.Command("docker", dockerArgs...)
	dockerCmd.Stdout = os.Stdout
	dockerCmd.Stderr = os.Stderr
	dockerCmd.Stdin = os.Stdin
	// Pass the resolved token to docker compose via env; the compose file
	// interpolates ${REPLICATED_API_TOKEN} so it lands inside the container.
	// Keeping it out of the compose file on disk avoids leaking secrets there.
	dockerCmd.Env = append(os.Environ(),
		"REPLICATED_API_TOKEN="+token,
		"EP_PREVIEW_CUSTOMERS_JSON="+customersB64,
	)

	if err := dockerCmd.Run(); err != nil {
		// Clean up compose file on error
		os.Remove(composePath)
		// Don't wrap Ctrl+C exits as errors. Docker Compose may either exit
		// 130 explicitly (128 + SIGINT; older behavior) or re-raise the signal
		// and die from it (newer behavior). In the signal case, ExitCode()
		// returns -1 and we have to inspect the syscall wait status to know
		// it was SIGINT vs some other signal.
		if isInterrupt(err) {
			return nil
		}
		return errors.Wrap(err, "docker compose up")
	}

	// Clean up compose file when done
	os.Remove(composePath)
	return nil
}

// previewLicense mirrors the fields portal-components' fetchLicense reads off
// the /enterprise-portal/license envelope. Kept in sync with the LicenseResponse
// struct in handlers/market-api/enterpriseportal/license.go.
type previewLicense struct {
	ID                                string                   `json:"id"`
	AppID                             string                   `json:"appId"`
	AppName                           string                   `json:"appName"`
	AppIcon                           *string                  `json:"appIcon"`
	Channels                          []previewLicenseChannel  `json:"channels"`
	CustomerID                        string                   `json:"customerId"`
	CustomerName                      string                   `json:"customerName"`
	CustomerEmail                     string                   `json:"customerEmail"`
	CreatedAt                         string                   `json:"createdAt"`
	UpdatedAt                         string                   `json:"updatedAt"`
	ExpireAt                          *string                  `json:"expireAt"`
	IsExpired                         bool                     `json:"isExpired"`
	IsArchived                        bool                     `json:"isArchived"`
	LicenseType                       string                   `json:"licenseType"`
	Sequence                          int64                    `json:"sequence"`
	IsAirgapSupported                 bool                     `json:"isAirgapSupported"`
	IsGitopsSupported                 bool                     `json:"isGitopsSupported"`
	IsIdentityServiceSupported        bool                     `json:"isIdentityServiceSupported"`
	IsGeoaxisSupported                bool                     `json:"isGeoaxisSupported"`
	IsSnapshotSupported               bool                     `json:"isSnapshotSupported"`
	IsDisasterRecoverySupported       bool                     `json:"isDisasterRecoverySupported"`
	IsSupportBundleUploadSupported    bool                     `json:"isSupportBundleUploadSupported"`
	IsEmbeddedClusterDownloadEnabled  bool                     `json:"isEmbeddedClusterDownloadEnabled"`
	IsEmbeddedClusterMultiNodeEnabled bool                     `json:"isEmbeddedClusterMultiNodeEnabled"`
	IsKotsInstallEnabled              bool                     `json:"isKotsInstallEnabled"`
	IsHelmInstallEnabled              bool                     `json:"isHelmInstallEnabled"`
	IsKurlInstallEnabled              bool                     `json:"isKurlInstallEnabled"`
	IsHelmAirgapEnabled               bool                     `json:"isHelmAirgapEnabled"`
	EntitlementFields                 []previewEntitlementField `json:"entitlementFields"`
	EntitlementValues                 []previewEntitlementValue `json:"entitlementValues"`
}

type previewLicenseChannel struct {
	AppID                 string  `json:"appId"`
	LicenseID             string  `json:"licenseId"`
	ChannelID             string  `json:"channelId"`
	ChannelName           string  `json:"channelName"`
	ChannelSlug           string  `json:"channelSlug"`
	IsSemverRequired      int     `json:"isSemverRequired"`
	IsDefault             int     `json:"isDefault"`
	PinnedChannelSequence *int64  `json:"pinnedChannelSequence"`
	HasKurlInstaller      bool    `json:"hasKurlInstaller"`
}

type previewEntitlementField struct {
	Name       string `json:"name"`
	Title      string `json:"title"`
	Type       string `json:"type"`
	Required   int    `json:"required"`
	Hidden     int    `json:"hidden"`
	DefaultVal string `json:"defaultVal"`
}

type previewEntitlementValue struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

// buildPreviewCustomersEnv fetches the app + its customers from the vendor API
// and returns a base64-encoded JSON array of License-shaped objects suitable
// for the EP_PREVIEW_CUSTOMERS_JSON env var.
func buildPreviewCustomersEnv(appSlug, token string) (string, error) {
	httpClient := platformclient.NewHTTPClient(platformOrigin, token)
	client := &kotsclient.VendorV3Client{HTTPClient: *httpClient}

	app, err := client.GetApp(context.TODO(), appSlug, true)
	if err != nil {
		return "", errors.Wrap(err, "get app")
	}
	if app == nil {
		return "", errors.Errorf("app %q not found", appSlug)
	}

	customers, err := client.ListCustomers(app.ID, false)
	if err != nil {
		return "", errors.Wrap(err, "list customers")
	}

	out := make([]previewLicense, 0, len(customers))
	for _, cust := range customers {
		out = append(out, customerToPreviewLicense(app, cust))
	}

	raw, err := json.Marshal(out)
	if err != nil {
		return "", errors.Wrap(err, "encode customers")
	}
	return base64.StdEncoding.EncodeToString(raw), nil
}

func customerToPreviewLicense(app *types.App, c types.Customer) previewLicense {
	channels := make([]previewLicenseChannel, 0, len(c.Channels))
	for _, ch := range c.Channels {
		channels = append(channels, previewLicenseChannel{
			AppID:       app.ID,
			LicenseID:   c.InstallationID,
			ChannelID:   ch.ID,
			ChannelName: ch.Name,
			ChannelSlug: ch.Slug,
		})
	}

	values := make([]previewEntitlementValue, 0, len(c.Entitlements))
	for _, e := range c.Entitlements {
		values = append(values, previewEntitlementValue{Name: e.Name, Value: e.Value})
	}

	var expireAt *string
	isExpired := false
	if c.Expires != nil {
		s := c.Expires.Format("2006-01-02T15:04:05.000Z")
		expireAt = &s
		isExpired = c.Expires.Before(time.Now())
	}

	return previewLicense{
		ID:                                c.InstallationID,
		AppID:                             app.ID,
		AppName:                           app.Name,
		Channels:                          channels,
		CustomerID:                        c.ID,
		CustomerName:                      c.Name,
		CustomerEmail:                     c.Email,
		ExpireAt:                          expireAt,
		IsExpired:                         isExpired,
		LicenseType:                       c.Type,
		IsAirgapSupported:                 c.IsAirgapEnabled,
		IsGitopsSupported:                 c.IsGitopsSupported,
		IsIdentityServiceSupported:        c.IsIdentityServiceSupported,
		IsGeoaxisSupported:                c.IsGeoaxisSupported,
		IsSnapshotSupported:               c.IsSnapshotSupported,
		IsSupportBundleUploadSupported:    c.IsSupportBundleUploadEnabled,
		IsEmbeddedClusterDownloadEnabled:  c.IsEmbeddedClusterDownloadEnabled,
		IsEmbeddedClusterMultiNodeEnabled: c.IsEmbeddedClusterMultinodeEnabled,
		IsKotsInstallEnabled:              c.IsKotsInstallEnabled,
		EntitlementFields:                 []previewEntitlementField{},
		EntitlementValues:                 values,
	}
}

// findFreePort returns the first port starting at `start` (inclusive) that
// nothing is already serving on `localhost`. Checks up to `attempts`
// consecutive ports.
//
// We probe by trying to *connect* rather than *bind* because bind-probes miss
// half-busy ports: Node's default IPV6_V6ONLY means a Next.js dev server on
// IPv6 *:3000 doesn't block an IPv4 127.0.0.1:3000 bind, so the probe
// succeeds and we hand back a port that docker can grab — ending up with two
// listeners on "localhost:3000" that randomly split traffic based on resolver
// order. A connect-probe asks the same question the browser does: "if I dial
// localhost:3000, does anything answer?" and works regardless of which
// address family the listener is on.
func findFreePort(start, attempts int) (int, error) {
	for p := start; p < start+attempts; p++ {
		if !portBusy(p) {
			return p, nil
		}
	}
	return 0, errors.Errorf("no free port found in range %d–%d", start, start+attempts-1)
}

func portBusy(p int) bool {
	for _, addr := range []string{
		fmt.Sprintf("127.0.0.1:%d", p),
		fmt.Sprintf("[::1]:%d", p),
	} {
		c, err := net.DialTimeout("tcp", addr, 100*time.Millisecond)
		if err == nil {
			_ = c.Close()
			return true
		}
	}
	return false
}

// escapeComposeScalar escapes a string for use as a YAML single-quoted scalar
// inside a docker-compose file. Two layers:
//   - YAML single-quote: ' → ''
//   - docker-compose variable interpolation: $ → $$. Compose interpolates $vars
//     over the whole file before YAML parsing, single-quoted strings included,
//     so a path like /Users/ca$h/repo would otherwise have "$h" treated as a
//     variable reference and silently corrupted.
func escapeComposeScalar(s string) string {
	s = strings.ReplaceAll(s, "$", "$$")
	s = strings.ReplaceAll(s, "'", "''")
	return s
}

// isInterrupt reports whether the error from cmd.Run() came from a Ctrl+C.
// Covers both shapes: exit code 130 (shell convention, older docker compose)
// and processes killed directly by SIGINT (newer docker compose re-raises
// the signal). On Unix, signal-killed processes report ExitCode() == -1 and
// the signal info lives on syscall.WaitStatus.
func isInterrupt(err error) bool {
	exitErr, ok := err.(*exec.ExitError)
	if !ok {
		return false
	}
	if exitErr.ExitCode() == 130 {
		return true
	}
	if ws, ok := exitErr.Sys().(syscall.WaitStatus); ok && ws.Signaled() && ws.Signal() == syscall.SIGINT {
		return true
	}
	return false
}
