name: CI

on:
  push:
    paths:
    - '**'
    - '!**.md'
    - '!doc/**'
    - '!**.png'

jobs:

  make-tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
      - name: Install pact
        run: |
          curl -LO https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v1.91.0/pact-1.91.0-linux-x86_64.tar.gz
          tar -zxvf pact-1.91.0-linux-x86_64.tar.gz
          sudo mv pact /usr/local/bin
          echo "/usr/local/bin/pact/bin" >> $GITHUB_PATH
      - name: make test
        run: make test
  make-build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18'
      - name: make build
        run: make build
