name: CI

on:
  push:
    paths:
    - '**'
    - '!**.md'
    - '!doc/**'
    - '!**.png'

jobs:
  make-tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: make test
        run: make test
  install-pact:
    runs-on: ubuntu-20.04
    steps:
      - run: |
        echo "-----> Install pact"
        curl -LO https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v1.69.0/pact-1.69.0-linux-x86_64.tar.gz
        tar -zxvf pact-1.69.0-linux-x86_64.tar.gz
        sudo mv pact /usr/local/bin
        echo "export PATH=/usr/local/bin/pact/bin:\$PATH" | sudo tee -a /etc/profile > /dev/null
  make-build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.18'
      - name: make test
        run: make test
