name: CI

on:
  push:
    paths:
    - '**'
    - '!**.md'
    - '!doc/**'
    - '!**.png'

jobs:
  make-pacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: make pacts
        run: make pacts
  make-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: make test
        run: make test
        env:
          REPLICATED_API_ORIGIN: https://api.replicated.com/vendor
          REPLICATED_ID_ORIGIN: https://id.replicated.com
          REPLICATED_API_TOKEN: ${{ secrets.REPLICATED_API_TOKEN }}
  make-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: make build
        run: make build
  snyk-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/golang@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
  snyk-monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/golang@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
