name: Import secrets and variables to Depot CI
on: push

permissions:
  id-token: write
  contents: read

jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: depot/setup-action@v1
      - name: Import secrets
        env:
          DOCS_REPO_TOKEN: ${{ secrets.DOCS_REPO_TOKEN }}
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
          REPLICATED_API_TOKEN: ${{ secrets.REPLICATED_API_TOKEN }}
          VENDOR_USER_PASSWORD: ${{ secrets.VENDOR_USER_PASSWORD }}
          DD_API_KEY: ${{ secrets.DD_API_KEY }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}
          OKTETO_TOKEN: ${{ secrets.OKTETO_TOKEN }}
          PACT_BROKER_BASE_URL: ${{ secrets.PACT_BROKER_BASE_URL }}
          PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}
          REPLICATED_GH_PAT: ${{ secrets.REPLICATED_GH_PAT }}
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          unset DEPOT_TOKEN
          depot ci secrets add DOCS_REPO_TOKEN="$DOCS_REPO_TOKEN" HOMEBREW_TAP_GITHUB_TOKEN="$HOMEBREW_TAP_GITHUB_TOKEN" REPLICATED_API_TOKEN="$REPLICATED_API_TOKEN" VENDOR_USER_PASSWORD="$VENDOR_USER_PASSWORD" DD_API_KEY="$DD_API_KEY" DOCKERHUB_PASSWORD="$DOCKERHUB_PASSWORD" DOCKERHUB_USER="$DOCKERHUB_USER" FOSSA_API_KEY="$FOSSA_API_KEY" OKTETO_TOKEN="$OKTETO_TOKEN" PACT_BROKER_BASE_URL="$PACT_BROKER_BASE_URL" PACT_BROKER_TOKEN="$PACT_BROKER_TOKEN" REPLICATED_GH_PAT="$REPLICATED_GH_PAT" SNYK_TOKEN="$SNYK_TOKEN" --repo replicatedhq/replicated
  variables:
    runs-on: ubuntu-latest
    steps:
      - uses: depot/setup-action@v1
      - name: Import variables
        env:
          PACT_BROKER_BASE_URL: ${{ vars.PACT_BROKER_BASE_URL }}
        run: |
          unset DEPOT_TOKEN
          depot ci vars add PACT_BROKER_BASE_URL="$PACT_BROKER_BASE_URL" --repo replicatedhq/replicated
