name: Working branch CI

on:
  push:
    paths:
      - '**'
      - '!**.md'
      - '!doc/**'
      - '!**.png'
    branches-ignore:
      - main

jobs:
  make-tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.20'
      - uses: replicatedhq/action-install-pact@v1
      - name: make test
        run: make test
  make-build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.20'
      - name: make build
        run: make build
